# Generated by Django 2.2.5 on 2019-10-15 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseTitle', models.TextField(max_length=200)),
                ('courseDescription', models.TextField(max_length=500)),
                ('hours', models.IntegerField(default=112)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserCreator', to=settings.AUTH_USER_MODEL)),
                ('userMap', models.ManyToManyField(null=True, related_name='LearnersEnrolled', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Weeks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekTitle', models.TextField(max_length=100)),
                ('weekVideo', models.FileField(null=True, upload_to='videos/', verbose_name='')),
                ('weekDesc', models.TextField(max_length=200)),
                ('courseDet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Course')),
            ],
        ),
        migrations.CreateModel(
            name='ExtendUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(default='images/no-img.jpg', upload_to='images')),
                ('isStudent', models.BooleanField(default=False, verbose_name='Student')),
                ('isInstructor', models.BooleanField(default=False, verbose_name='Instructor')),
                ('userKey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
