# Generated by Django 2.2.5 on 2019-10-12 03:39

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseTitle', models.TextField(max_length=200)),
                ('courseDescription', models.TextField(max_length=500)),
                ('hours', models.IntegerField(default=200)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserCreator', to=settings.AUTH_USER_MODEL)),
                ('userMap', models.ManyToManyField(related_name='LearnersEnrolled', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Weeks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekTitle', models.TextField(max_length=100)),
                ('weekVideo', models.FileField(null=True, upload_to='videos/', verbose_name='')),
                ('courseDet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Course')),
            ],
        ),
        migrations.CreateModel(
            name='ExtendUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile', models.ImageField(default='../media/images/no-img.jpg', upload_to='../media/images')),
                ('isInstructor', models.BooleanField(default=False)),
                ('userKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserExtend', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
